frmt done, fixed notifications for mnt scripts, color change in i3

diff --git a/.local/bin/frmt b/.local/bin/frmt
--- a/.local/bin/frmt
+++ b/.local/bin/frmt
@@ -8,7 +8,7 @@
 # - Read a list of valid drives to format (everything connected, mounted or unmounted, that is not system, like home, root, boot and swap partitions)
 # - Ask for partition type and label and do everything else on its own.
 
-# Disclaimer: for the sake of simplicity I assume that the devices used have only one partition on them, so the script reads a partition 'e.g sdb1' to format the drive (sdb). For devices with more than one partition this script throws an error.
+# Disclaimer: for the sake of simplicity I assume that the devices used have only one partition on them, so the script reads a partition 'e.g sdb1' to format the drive (sdb). The script is untested for devices with more than one partition.
 
 # Options:
 # -d: device to format. Devices with more than one partition will not be accepted
@@ -21,19 +21,19 @@
 
 ### --HELP END-- ###
 
+# id for dunstify
+did=999111
+
 # valid devices
 valid_devices="$(lsblk -nPo "path,label,size,type,mountpoint" | awk '$4~/part/ && $5 !~ /SWAP|"\/boot"|"\/home"|"\/"/ {for (i=1;i<=3;i++) sub(/.*=/, "",$i);printf "%s %s (%s)\n",$1,$2,$3}' | tr -d '"' | sed 's/  / /')"
 
 valid_types="$(printf "fat32\nexfat\nntfs\next4")"
 
-echo Devices to format: "$valid_devices"
-echo Valid types: "$valid_types"
-
 scriptfail() { \
 	       failmsg="$1"
 	       exitcode="$2"
 	       echo "$failmsg" >&2
-	       notify-send "⚠ Format" "$failmsg"
+	       dunstify -r $did "⚠ Format" "$failmsg"
 	       exit $exitcode
 }
 
@@ -45,7 +45,6 @@ while getopts ":d:l:t:h" opt; do
 	    # ensure DEVICE refers to a path -- then check for validity 
 	    echo "$DEVICE" | grep -q '^\/dev\/' || DEVICE="/dev/$DEVICE"
 	    echo "$valid_devices" | grep -qw "$DEVICE" || scriptfail "$DEVICE is not valid!" 1
-	    test -z "$(lsblk -no "path,mountpoint" | grep "$DEVICE" | awk '{print $2}')" && scriptfail "$DEVICE is mounted! Unmount it first." 1
 	    ;;
 	l)
 	    LABEL="$OPTARG"
@@ -85,9 +84,10 @@ else
     LABEL="$(lsblk -no path,label | grep -w "$DEVICE" | awk '{print $2}')"
 fi
 
-# what we need is the device not the partition
-DEVICE="$(echo "$DEVICE" | sed 's/[0-9]$//')"
-test "$(lsblk -no path,type | grep part | grep "$DEVICE" | wc -l)" -gt 1 && scriptfail "$DEVICE has more than one partitions!" 1
+test -n "$(lsblk -no "path,mountpoint" | grep "$DEVICE" | awk '{print $2}')" && scriptfail "$DEVICE is mounted! Unmount it first." 1
+
+P_DEVICE="/dev/$(lsblk -no pkname "$DEVICE")"
+test "$(lsblk -no path,type | grep part | grep "$P_DEVICE" | wc -l)" -gt 1 && scriptfail "$DEVICE has more than one partitions!" 1
 
 # choose fstype
 if test -z "$FSTYPE"; then
@@ -98,7 +98,47 @@ if test -z "$NEWLABEL"; then
     NEWLABEL="$(echo "$LABEL" | dmenu -i -p "Rename drive (defaults to $LABEL):")" || NEWLABEL="$LABEL"
 fi
 
-echo "formatting $DEVICE into $FSTYPE drive named $NEWLABEL"
+case "$FSTYPE" in
+    "fat32")
+	test -n "$NEWLABEL" && labopt="-n"
+	frmtcmd=(mkfs.vfat -F 32)
+	;;
+    "exfat")
+	test -n "$NEWLABEL" && labopt="-n"
+	frmtcmd=(mkfs.exfat)
+	;;
+    "ext4")
+	test -n "$NEWLABEL" && labopt="-L"
+	frmtcmd=(mkfs.ext4)
+	;;
+    "ntfs")
+	test -n "$NEWLABEL" && labopt="-L"
+	frmtcmd=(mkfs.ntfs)
+	# mfks.ntfs takes considerably more time to finish
+	;;
+    *)
+	scriptfail "$FSTYPE is not a valid filesystem!" 1
+	;;
+esac
 
-# TODO: ensure NEWLABEL is valid
-# TODO: the actual format command
+size="$(lsblk -no path,size | grep -w "$P_DEVICE" | awk '{print $2}')"
+
+yornformat="$(printf "Yes\nNo" | dmenu -i -p "Will format $DEVICE ($size) to $FSTYPE filesystem labeled $NEWLABEL. Proceed?")" || scriptfail "Aborted by user." 2
+
+test "$FSTYPE" == "ntfs" && dunstify -r $did " Format" "This will take some time..."
+
+case "$yornformat" in
+    "Yes")
+	sudo -A parted "$P_DEVICE" -s --align opt mklabel msdos 0 "$size" >/dev/null
+	test $? -ne 0 && scriptfail "First parted command failed!" 1 || \
+		sudo -A parted "$P_DEVICE" -s -a opt mkpart primary 2048s "$size" >/dev/null
+	test $? -ne 0 && scriptfail "Second parted command failed!" 1 || \
+		sudo -A $frmtcmd $labopt "$NEWLABEL" "$DEVICE"
+	test $? -ne 0 && scriptfail "Format failed at the mkfs command!" 1 || \
+		dunstify -r $did " Format" "$DEVICE $NEWLABEL ($size) formatted to $FSTYPE filesystem"
+	exit
+	;;
+    *)
+	scriptfail "Aborted bu user." 2
+	;;
+esac
