fixed some scripts

diff --git a/scripts/download_stuff b/scripts/download_stuff
--- a/scripts/download_stuff
+++ b/scripts/download_stuff
@@ -11,7 +11,9 @@ link=$(xclip -selection clipboard -o)
 if [ $(echo $link | grep "^magnet") ] ; then
     transmission-remote -a "$link" && notify-send "  Downloading torent" && (pgrep -f "urxvt -e tremc" && i3-msg "[title=tremc] focus" || urxvt -e tremc &) && exit 0 || notify-send "  Something went wrong!" && exit 1
 
+    # assuming that all links refer to downloadable links -- TODO: use youtube-dl to give errors for non-valid URLs
 elif [ $(echo $link | grep "^http") ] ; then
+    f_name=$(youtube-dl -e "$link") # this takes extra time, but is cool dammit!
     type=$(printf "audio\nvideo" | dmenu -i -p "Download audio or video?")
     if [ $type = "audio" ] ; then
 	audopt="-x --audio-format mp3"
@@ -21,8 +23,8 @@ elif [ $(echo $link | grep "^http") ] ; then
 	notify-send "  Download aborted" && exit 1
     fi
 
-    notify-send "  Downloading $type"
-    youtube-dl $audopt -i -c -o "$(echo $dl_dir)/%(title)s.%(ext)s" "$(echo $link)" && notify-send "  Downloading $type complete" && exit 0 || notify-send "  Downloading $type failed!" && exit 1
+    notify-send "  Downloading $type \"$f_name\""
+    youtube-dl $audopt -i -c -o "$(echo $dl_dir)/%(title)s.%(ext)s" "$(echo $link)" && notify-send "  \"$f_name\" download complete" && exit 0 || notify-send "  \"$f_name\" download failed!" && exit 1
 
 else
     notify-send "  No valid link in clipboard!" && exit 1
